--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/OutiServer/Casino
build-by-default: true
branches:
- master
projects:
  Casino:
    path: ""
    lint:
      phpstan: false
    libs:
      - src: poggit/libasynql/libasynql
        version: ^4.1.0
      - src: CortexPE/Commando/Commando
        version: ^3.0.0
        branch: PM4
...
