name: EconomyCasino
description: カジノプラグイン
version: 1.0.0
api: 4.0.0
main: outiserver\casino\CasinoMain
src-namespace-prefix: outiserver\casino

loadbefore:
  - EconomyCore

permissions:
  casino.command:
    description: Casino Command Permission
    default: true
  casino.createslotmanager.command:
    description: CreateSlotManager Command Permission
    default: op